version: '3'

services:

  Ganache:
    container_name: dev_ganache
    image: trufflesuite/ganache-cli
    command: --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --debug --verbose --networkId 7777 --db /data
    restart: always
    volumes:
    - ./dev_ganache:/data
    ports:
    - "8545:8545"

  EthereumBridge:
    container_name: dev_ethereum_bridge
    image: cryptomental/ethereum-bridge
    command: -H dev_ganache:8545 -a 9 --dev
    restart: always
    links:
    - "Ganache:dev_ganache"
    depends_on:
    - Ganache
